Repository jupyterlab/jupyterlab-github, pull requests merged in 2018-04, with the labels that each got.

#44 Updates for JupyterLab v0.32
  README.md
  package.json
Labels: type:Maintenance

#47 Change to using access tokens and make the api url configurable.
  jupyterlab_github/__init__.py
Labels: tag:GitHub Integration, tag:Server Extension, type:Enhancement

#48 Allow for private repos to be viewed if the user is authenticated.
  jupyterlab_github/__init__.py
  src/contents.ts
Labels: tag:GitHub Integration, type:Enhancement

#50 Allow setting a default repository at launch.
  README.md
  package.json
  schema/drive.json
  src/index.ts
Labels: type:Enhancement

#51 Conditionally use err.response.
  jupyterlab_github/__init__.py
Labels: type:Bug
